# Generated by Django 5.0.2 on 2024-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
